package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type ProductCodeMap struct {
	Name  string
	Id    int64
	Image string
}

func generateLuauCode(products *map[int64]ProductCodeMap, passes *map[int64]ProductCodeMap) string {
	var builder strings.Builder
	builder.WriteString("-- Autogenerated by jaxon CLI\n")
	builder.WriteString("local Products = {\n")
	builder.WriteString("\tProducts = {\n")

	for _, product := range *products {
		fmt.Fprintf(&builder,
			"\t\t[\"%s\"] = {\n\t\t\tName = \"%s\",\n\t\t\tId = %d,\n\t\t\tImage = \"%s\"\n\t\t},\n",
			product.Name,
			product.Name,
			product.Id,
			product.Image,
		)
	}

	builder.WriteString("\t},\n")

	builder.WriteString("\tGamepasses = {\n")

	for _, pass := range *passes {
		fmt.Fprintf(&builder,
			"\t\t[\"%s\"] = {\n\t\t\tName = \"%s\",\n\t\t\tId = %d,\n\t\t\tImage = \"%s\"\n\t\t},\n",
			pass.Name,
			pass.Name,
			pass.Id,
			pass.Image,
		)
	}

	builder.WriteString("\t},\n")

	builder.WriteString("\tProductsById = {},\n")
	builder.WriteString("\tGamepassesById = {},\n")

	builder.WriteString("},\n")

	builder.WriteString("\nfor _,product in Products.Products do\n\t\tProducts.ProductsById[product.Id] = product\nend\n")

	builder.WriteString("\nfor _,gamepass in Products.Gamepasses do\n\t\tGamepasses.GamepassesById[gamepass.Id] = gamepass\nend\n")

	builder.WriteString("\nreturn Products")

	return builder.String()
}

func generateTypescriptDef() string {
	return ""
}

func GenerateCode(products *map[int64]ProductCodeMap, passes *map[int64]ProductCodeMap) {
	fileName := AppConfig.Files.FileName
	if fileName == "" {
		fileName = "products"
	}

	luauFilePath := filepath.Join(AppConfig.Files.Output, fileName+".luau")

	var code string = generateLuauCode(products, passes)

	if AppConfig.Generation.Typescript {
		typescriptFilePath := filepath.Join(AppConfig.Files.Output, fileName+".d.ts")

		var tsCode string = generateTypescriptDef()

		os.WriteFile(typescriptFilePath, []byte(tsCode), 0644)
	}

	os.WriteFile(luauFilePath, []byte(code), 0644)
}
